apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gitops-helm-demo
  namespace: gitops-helm
  annotations:
    # Container Image Automated Updates
    fluxcd.io/automated: "true"
spec:
  releaseName: gitops-helm-demo
  chart:
    git: git@github.com:terrificdm/config-repo
    ref: master
    path: charts/gitops-helm-demo
  values:
    image:
      repository: 634072196806.dkr.ecr.cn-north-1.amazonaws.com.cn/gitops-app-demo
      tag: a2f224c
